// <auto-generated />
namespace Subvault_Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreItemmanytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreItemmanytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201706281007525_Genre Item many to many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
