// <auto-generated />
namespace Subvault_Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Itemadditionalattributesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Itemadditionalattributesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201706271403399_Item additional attributes added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
